name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-xetex librsvg2-bin

      - name: Run
        working-directory: VkGuideDev.Scrapper
        run: |
          COUNT=$(dotnet run .)
          
          echo "Count: $COUNT"
          
          CMD=(pandoc)
          for ((i=0; i<COUNT; i++)); do
            FILE="${i}.html"
            CMD+=("$FILE")
          done
          
          CMD+=(-o "output.pdf" --pdf-engine=xelatex)

          ls

          echo "Running command: ${CMD[*]}"
          "${CMD[@]}"

          ls

      - name: Upload PDF
        working-directory: VkGuideDev.Scrapper
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: output.pdf
